### ISSUE TITLE
There's no way to pass --ssh flag when building image use image_resource vito/oci-build-task

### ISSUE THREAD

**Issue by ZozoZoeLi** [concourse/concourse-chart#136]
Hi Vito,

Here's a frustrating issue. In my Dockerfile, some pip dependencies come from private repositories. For a manual build, I pass the key as the following:

1. Inside Dockerfile 
`RUN --mount=type=ssh,id=github_ssh_key $VIRTUAL_ENV/bin/pip3 install -U -r ./hats/requirements-test.txt`
2. When executing `docker` command
`DOCKER_BUILDKIT=1 d build --progress=plain -t image:tag -f Dockerfile github_ssh_key=<PATH-TO-KEY>/.`

Now, my Concourse uses K8s credentials manager as it runs as Helm Chart. My job looks like the following:

```
jobs:

- name: build-image
  plan:
  - get: repo
  - task: build-image-task
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: repo
      outputs:
      - name: image
      run:
        path: build
      caches:
      - path: cache
      params:
        CONTEXT: repo
        BUILD_ARG_ssh: github_ssh_key=((github-key))
```
`((github-key))` is a K8s secret resource.

I was hoping the line `BUILD_ARG_ssh: github_ssh_key=((github-key))` could pass the ssh flag as `--ssh github_ssh_key=<MY-KEY>`, but I only realized that the `--ssh` flag only accepts the path to the key, not the key value. Now since I'm using K8s credentials manager from Helm Chart, I have no idea how to find the path to the key.
