### ISSUE TITLE
deployment not working

### ISSUE THREAD

**Issue by schmurfy** [concourse/concourse-chart#151]
I tried deploying concourse with this chart on my test cluster (gke) with traefik v1 installed using this config:

```yaml
web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - <xxx>


secrets:
  githubClientId: zzz
  githubClientSecret: yyy
  localUsers: ""

worker:
  replicas: 1
  minAvailable: 1

concourse:
  web:
    externalUrl: "https://<xxx>"
    auth:
      mainTeam:
        github:
          user: schmurfy
      github:
        enabled: true
  worker:
    baggageclaim:
      driver: overlay
    

```

The installation appears to work fine, I can login, set a new pipeline and it shows on the ui but after I got strange things and I can't find why.

I thought it was my pipeline so I grabbed the hello-world pipeline from the concourse examples, the set worked, I then unpaused it and it works too but then I tried running a new build and:
- the ui shows "Loading..." and never show anything else
- the color indicator turns to green after some point
- if I check the logs of the web process I see no errors, the workers shows everything was indeed executed

That's my first attempt at running concourse on kubernetes but I already used it in a different environnement.

PS: I tried an older version of concourse just in case but it behaves exactly the same with 6.2.0

Edit: I also tried `fly -t xxx execute -c task.yml` with the hello world task but it hangs indefinitely
