### ISSUE TITLE
Login via keycloak

### ISSUE THREAD

**Issue by hsok85** [concourse/concourse-chart#158]

**Comment by meezaan** [comment]
It works if you use OIDC or oAuth.

However, adding users to the main team does not work. I haven't raised a bug yet because I think I might be at fault.

But here is the config with which I can login, but I can't actually get access to main:

```
secrets:
  oidcClientId: client-id
  oidcClientSecret: secret

  auth:
    mainTeam:
        ## Authentication (Main Team) (OIDC), but this bit actually does not work
        ##
        oidc:

          ## Comma-separated allow list of OIDC users.
          ##
          user: user1,user2

          ## Comma-separated allow list of OIDC groups.
          ##
          group: administrators

## Authentication (OIDC)
      oidc:
        enabled: true

        ## The auth provider name displayed to users on the login page
        ##
        displayName: Some name

        ## (Required) An OIDC issuer URL that will be used to discover provider configuration using the .wellKnown/openid-c 
       configuration
        ##
        issuer: https://keycloak.example.com/auth/realms/<<realm>>

        ## Any additional scopes that need to be requested during authorization
        ##
        scope: profile offline_access

        ## The groups key indicates which claim to use to map external groups to Concourse teams.
        ##
        groupsKey: groups

        ## CA Certificate
        ##
        useCaCert:

        ## Skip SSL validation
        ##
        skipSslValidation:

        ## The user name key indicates which claim to use to map an external user name to a
        ## Concourse user name.
        ##
        userNameKey:

```
