### ISSUE TITLE
specify PersistentVolume selector in postgres.persistence

### ISSUE THREAD

**Issue by x3nb63** [concourse/concourse-chart#162]
My cluster has a `staticdisk` StorageClass where the volumes do not get created by a provisioner.

I normally handle this by writing `PersistentVolume` and `PersistentVolumeClaim` specs manually, where the claim has a `selector` that finds the volume by label, like:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-data
  namespace: ci
...
spec:
  storageClassName: staticdisk
  selector:
    matchLabels:
      name: "ci-data"
...
```

This would work with your chart too, if I could add a selector to the claim that it generates. (the volume itself would remain my problem / outside the scope of the chart)

As far as I tried its not possible right now.
