### ISSUE TITLE
spec.clusterIP: Invalid value: \"None\"

### ISSUE THREAD

**Issue by acarsercan** [concourse/concourse-chart#187]
Hi,

Running helm chart version: 14.3.0

```
    web:
      service:
        workerGateway:
          type: LoadBalancer
          annotations:
```
Error I'm seen
```
info="error updating the resource \"concourse-web\":\n\t cannot patch \"concourse-web\" with kind Service: Service \"concourse-web\" is invalid: spec.clusterIP: Invalid value: \"None\": field is immutable" targetNamespace=concourse release=concourse
```

Regards
