### ISSUE TITLE
Install certificates to worker that all containers could inherit from

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse-chart#211]
Currently Concourse supports specify CAs in docker resource source configure to allow the resource container to access a private registry. It also provide a flag `--certs-dir` to allow [cert propagation](https://concourse-ci.org/implementing-resource-types.html#resource-certs). 

But that is not the case for task container. A work around is to have a step to modify the task image to [include](https://docs.pivotal.io/platform-automation/v4.4/tasks.html#prepare-image) the custom certs before using it. The down side is one has to either prepare that image in a different job and upload it before using it; or the step has to be ran in each individual job.

If we could find a way in helm to append custom certs to worker's certificate directory, then there is no need to either configuring `--certs-dir` or modifying the task image beforehand. All containers of that worker will have certs inherit from worker itself.

**Comment by jknipper** [comment]
I found a way to add certificates without changing any images by preparing them in an init container and share them between containers.. This is even possible with the current chart. The important values for this look something like this:
```
worker:
  additionalVolumeMounts:
  - name: certificates
    mountPath: /etc/ssl/certs
  additionalVolumes:
  - name: certificates
    emptyDir: {}
  additionalCertificates: true
  extraInitContainers:
  - name: certificates
    image: concourse/concourse:7.4.0
    command:
    - /bin/sh
    args:
    - -ec
    - |-
      cp /worker-certs.pem/worker-certs.pem /usr/local/share/ca-certificates/sap.crt
      update-ca-certificates
      cp /etc/ssl/certs/ca-certificates.crt /certs
    volumeMounts:
    - name: certificates
      mountPath: /certs
    - name: worker-certs
      mountPath: /worker-certs.pem
secrets:
  workerAdditionalCerts: |-
    ...
```
Maybe the init container can be even added to the chart when additional certificates are set.
