### ISSUE TITLE
web.service.api.NodePort not honored

### ISSUE THREAD

**Issue by DonBower** [concourse/concourse-chart#212]
In the charts/templates/web-api-svc.yaml file, line 39 checks for the existence of a value at .Values.web.service.api.**atcNodePort**, and then sets the nodePort: value on line 40 to .Values.web.service.api.**NodePort**.
It should check for the existence of .Values.web.service.api.**NodePort**, not .**atcNodePort**

Documentation for NodePort says:
Sets the nodePort for api when using NodePort

It Does not mention atcNodePort.

**Comment by DonBower** [comment]
This workaround produces a NodePort service at 30001, which is what is desired for my case:
```
web:
  replicas: 3
  service:
    api:
      type: NodePort
      atcNodePort: 30008
      NodePort: 30001
```
