### ISSUE TITLE
Setting secrets.localUsers Doesn't Add User to main Team

### ISSUE THREAD

**Issue by willisc7** [concourse/concourse-chart#216]
If I `helm install` concourse using secrets.localUsers, then when I do a subsequent `fly login` I get the following error after authentication: `error: you are not a member of 'main' or the team does not exist`. However, if I only remove secrets.localUsers and repeat the install I am able to login with test:test and its a member of the main team.

I am using the following values.yml:
```
concourse:
  web:
    externalUrl: "https://concourse.example.com"
web:
  ingress:
    enabled: true
    hosts:
      - concourse.example.com
    tls:
      - secretName: concourse-web-tls
        hosts:
          - concourse.example.com
secrets:
  localUsers: "foo:bar"
```
