### ISSUE TITLE
What's the correct way to deploy Concourse as a `Deployment` instead of StatefulSet

### ISSUE THREAD

**Issue by christopher-wong** [concourse/concourse-chart#255]
I tried configuring Concourse to use a deployment

```
worker:
  replicas: 24
  kind: StatefulSet
```

but saw a number of errors on the workers as well as in the UI
`find or create container on worker concourse-worker-786c4bdc76-ggxzt: failed to create volume`

What's the correct way to deploy Concourse as a `Deployment` instead of StatefulSet

**Comment by taylorsilva** [comment]
I think you probably have a few things wrong in your deployment. I'll give you a few pointers here that hopefully help.

First, I'm not sure if this was some typo or bad copy-paste on your end, but from your codeblock, the `kind` should be set to `Deployment`, not `StatefulSet`. That's definitely step one to using a deployment instead of a stateful set.

For the `failed to create volume` error, that sounds like a configuration issue with your worker. You should check the worker logs for any errors coming from the `baggageclaim` component.

**Comment by yatzek** [comment]
You need to configure an additional volume to get it to work as "Deployment", add to your values.yml file something like this:
```
worker:
  additionalVolumeMounts:
    - name: concourse-work-dir
      mountPath: /concourse-work-dir
  additionalVolumes:
    - name: concourse-work-dir
       emptyDir:
         sizeLimit: 200Gi
```
