### ISSUE TITLE
[Feature] Support for multiple worker groups with different configurations

### ISSUE THREAD

**Issue by pipeworks-asmith** [concourse/concourse-chart#274]
It would be great to be able to specify multiple sets of worker statefulsets, each with different configurations. Consider some implementation like:

```yaml
# values.yaml
concourse:
  workers:  # replacing concourse.worker
    default:  # this is the existing worker group
      <<: *existing-concourse-worker-map
    gpu-enabled:
      # this map merged on top of the default before templating
      tag: gpu-enabled

workers:  # replacing worker, whose new default values look like:
  default:
    <<: *existing-worker-map
  # with new groups added below
  gpu-enabled:
    # this map merged on top of the default before templating
    enabled: true
```

This would replace current solutions offered such as handling multiple Helm releases -- one containing all the components while the rest have `web.enabled=false` and `postgres.enabled=false`. Logically, a single Concourse cluster should be able to be managed by a single Helm release, and I think the added complexity from this feature would not outweigh the benefits.
