### ISSUE TITLE
issue is with configRBAC and auth config

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse-chart#46]
Hi, I am trying to deploy `5.8.0` using helm charts. While deploying it fails to enter configRBAC and config auth. I have entered like below but my web node is failing.

```
➜  ~ k logs po/concourse-web-58997b67fd-4xkjc
{"timestamp":"2020-01-09T11:45:59.269737359Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2020-01-09T11:45:59.339357808Z","level":"info","source":"atc","message":"atc.credential-manager.configured credentials manager","data":{"name":"kubernetes","session":"6"}}
error: default team auth not configured: error converting YAML to JSON: yaml: did not find expected ',' or ']'
{"timestamp":"2020-01-09T11:45:59.344813625Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":77408,"session":"1"}}
```
 

```
configRBAC:
  owner:
  - SetTeam
  - RenameTeam
  - DestroyTeam
```
```
      mainTeam:
        ## Configuration file for specifying team params.
        ## Ref: https://concourse-ci.org/managing-teams.html#setting-roles
        ##
        config:
          - name: owner
            local:
              users: ["admin"]
```

without setting the value helm install is failing.

```
error validating data: unknown object type "nil" in ConfigMap.data.config-rbac.yml; if you choose to ignore these errors, turn validation off with --validate=false
```
Can you please help , how to use this feature becasue document is not clear.
