### ISSUE TITLE
Login redirects to 127.0.0.1:8080

### ISSUE THREAD

**Issue by lukaspj** [concourse/concourse-chart#78]
Hi,

When I run this chart, access the web UI and attempt to login, the login redirects from my domain name to http://127.0.0.1:8080/sky/issuer/auth, which subsequently fails.
I do not have any issues with other links on the Concourse Web UI.

I have not found any way to configure the external hostname or IP. How would I go about this?

Worth to mention that I have not enabled this chart's ingress.

**Comment by lukaspj** [comment]
Nvm, my bad I found it.

I was `concourse.web.externalUrl`
I was looking for possible keys under the root-level `web` key

**Comment by karan-kapoor90** [comment]
I've tried setting the variable. but it's still not working for me. My config looks like this

```
concourse:
  web:
    clusterName: k8s  
    bindIp: 0.0.0.0      
    bindPort: 8080           
    localAuth:
      teams:
        - main                    
    auth:
      mainTeam:
        localUser: "god"     
    externalUrl: concourse.myhostname.com
secrets:  
  localUsers: "admin:password"   
```

What I'm trying to do is to expose my concourse externally on a public domain using nginx ingress controller. My ingress config looks like so:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: concourse-server-ingress
  namespace: default
spec:
  rules:
  - host: concourse.myhostname.com
    http:
      paths:
      - backend:
          serviceName: concourse-web
          servicePort: atc
```

The home page is available at concourse.myhostname.com, but as soon as I click on login, the URL changes to `127.0.0.1:8080` and site cannot connect. 

Note, port forwarding the standard clusterIp service for the concourse-web service works like a charm with no problems at all.
