### ISSUE TITLE
concourse 6.0 service monitor is not auto discoverd by prometheus operator

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse-chart#87]
Hello Colleagues,

I have enabled the Prometheus monitor as well as a scrapper. The concourse is running in my default namespace and Prometheus operator is running in monitoring namespace.

Not sure why the service monitor is not auto-discovered by the Prometheus Operator.

@
```
prometheus:
      enabled: true

      ## IP to listen on to expose Prometheus metrics.
      ##
      bindIp: "0.0.0.0"

      ## Port to listen on to expose Prometheus metrics.
      ##
      bindPort: 9391
      ## If Prometheus operator is used, also create a servicemonitor object
      serviceMonitor:
        enabled: true
        interval: "30s"
        # Namespace the servicemonitor object should be in
        namespace: monitoring
```

@KYannick  can you help with this issue ? Am i missing anythig ?

BRs, Gowrisankar
