### ISSUE TITLE
Include garden networkpool configuration

### ISSUE THREAD

**Issue by michyliao** [concourse/concourse-chart#88]
Hi there,

Are we able to include the env variable of CONCOURSE_GARDEN_NETWORK_POOL to be part of the helm chart? 

to support `--garden-network-pool` https://bosh.io/jobs/garden?source=github.com/cloudfoundry/garden-runc-release#p%3dgarden.network_pool 

ie.
```
 garden:
      ## Path to the 'gdn' executable (or leave as 'gdn' to find it in $PATH)
      ##
      bin: gdn

      ## Path to a config file to use for Garden in INI format.
      ##
      ## For example, in a ConfigMap:
      ##
      ##   [server]
      ##     max-containers = 100
      ##
      ## For information about the possible values:
      ## Ref: https://bosh.io/jobs/garden?source=github.com/cloudfoundry/garden-runc-release
      ##
      config:

      ## Enable a proxy DNS server for Garden
      ##
      dnsProxyEnable:

      ## Use the insecure Houdini Garden backend.
      ##
      useHoudini:

      ## How long to wait for requests to Garden to complete. 0 means no timeout.
      ##
      requestTimeout:

      ## Network range to use for dynamically allocated container subnets. (Default value: 10.254.0.0/22)
      ## Ref: https://bosh.io/jobs/garden?source=github.com/cloudfoundry/garden-runc-release#p%3dgarden.network_pool
      networkPool:

```
Thanks!

**Comment by cirocosta** [comment]
Hi @michyliao, thanks for filling the issue!

I think that config should not really be part of the set of values that we
expose directly in the `values.yaml` because that's not one of the flags that
Concourse exposes directly (e.g., do `concourse worker --help` and you'll not
see the flag there). Even though it's not there, it works because we do a
catch-all on `CONCOURSE_GARDEN` flags and then forward them to the `gdn` that we
launch.

Exactly for supporting these `gdn` configurations,
`concourse.worker.garden.config` and `worker.env` exists - so that
configurations that are outside of Concourse's knowledge can take place.

E.g.:

```yaml
concourse:
  worker:
    env:
    - name: CONCOURSE_GARDEN_NETWORK_POOL
      value: "10.254.0.0/16"
    - name: CONCOURSE_GARDEN_DENY_NETWORK
      value: "169.254.169.254/32"
```

https://github.com/concourse/hush-house/blob/72dc4f62df12fd0240b1af3c39b70f63d2c89527/deployments/with-creds/workers/values.yaml#L30-L36

Do you think it'd be enough if we had a more explicit documentation in
`README.md` that explicitly stated that garden-specific configurations could
take place in `worker.env`? Also, please let me know if you disagree with any of
the above 😁 

thanks!
